### ISSUE TITLE
DialogManager 만들기

### ISSUE THREAD

**Issue by lebmouse** [handy-candy/handycandy_client#6]
### Todo

- [x] 캔디 추가하기
![image](https://user-images.githubusercontent.com/49134038/124482222-0587cd00-dde4-11eb-90f3-59569dbd5907.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A5805
- [x] 카테고리 dropdown
![image](https://user-images.githubusercontent.com/49134038/124482250-0caedb00-dde4-11eb-881d-6727763ac9ab.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A5830
- [x] 캔디 추가 완료
![image](https://user-images.githubusercontent.com/49134038/124482279-120c2580-dde4-11eb-8c27-0269fb6ca358.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A5871
- [x] 날짜 설정
   - [ ] 다른 연도 클릭 시 `month`, `date` 버튼 비우기
![image](https://user-images.githubusercontent.com/49134038/124482312-1c2e2400-dde4-11eb-9a31-a32d53613980.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A5949
- [x] 날짜 dropdown
   - [ ] typeof date === string 으로 변경 및 코드 적용
   - [ ] 한자리 수일 경우 "0" 붙이기
![image](https://user-images.githubusercontent.com/49134038/124482340-22bc9b80-dde4-11eb-9383-11c3f308ea14.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A5971
- [x] 메시지 작성
![image](https://user-images.githubusercontent.com/49134038/124482362-28b27c80-dde4-11eb-85a8-b12e0e0e6d75.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A5934
- [x] 카테고리 추가
![image](https://user-images.githubusercontent.com/49134038/124482491-4c75c280-dde4-11eb-8e9e-0da624d30d58.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A6026
- [x] 카테고리 선택
![image](https://user-images.githubusercontent.com/49134038/124483158-fa816c80-dde4-11eb-82ba-45833ea1398f.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A6375
- [x] 카테고리 추가 완료
![image](https://user-images.githubusercontent.com/49134038/124483239-108f2d00-dde5-11eb-9479-ca66cfdf5185.png)
https://www.figma.com/file/Whu7vuuAOWiVLBTcPWY7RL/%ED%95%B8%EB%94%94%EC%BA%94%EB%94%94-Service-View_Final?node-id=497%3A6242
