### ISSUE TITLE
완료캔디 남은 서버에러 수정 후 연결 작업

### ISSUE THREAD

**Issue by juno7803** [handy-candy/handycandy_client#94]
### TODO
**[완료 상세]**
- [ ] 수정 모달 api 연결 (폼 만들기)
- [ ] 삭제 모달 api 연결 
- [ ] 감정 이모티콘 달기
- [ ] 카테고리에 따라 배너 바꾸기

**[완료]**
- [ ] 이미지 슬라이더 월 넣기
- [ ] 이미지 슬라이더 api 연결

**[공통]**
